# -*- coding: utf-8 -*-
"""HW_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yx2xoMziz90ka1TWolU3Up3ZBUbb6coi
"""

def WhoAmI():
  return('ys3889')

def get_bond_price(y,face,couponrate,m):
  pvcfsum=0
  cf=face*couponrate
  for t in range(1,m+1):
    pv=(1+y)**(-t)
    pvcf=pv*cf
    pvcfsum=pvcfsum+pvcf

  bondprice=pvcfsum+face*pv
  return(bondprice)

get_bond_price(0.03,2000000,0.04,10)

def getBondDuration(y,face,couponrate,m,ppy=1):
  pvcfsum=0
  wsum=0
  cf=face*(couponrate/ppy)
  y_period = y / ppy
  m_periods = m * ppy
  for t in range(1,m_periods+1):
    pv=(1+y_period)**(-t)
    cashflow=cf if t<m_periods else (face+cf)
    pvcf=pv*cashflow
    pvcfsum=pvcfsum+pvcf
    w=pvcf*t
    wsum=wsum+w

  bondprice=pvcfsum

  bondDuration=wsum/bondprice

  return(bondDuration)

getBondDuration(0.03,2000000,0.04,10,1)

def getBondPrice(face,couponrate,m,yc):
  pvcfsum=0
  cf=face*couponrate
  for t, y in enumerate(yc, start=1):
    pv=(1+y)**(-t)
    cashflow=cf if t<m else (face+cf)
    pvcf=pv*cashflow
    pvcfsum=pvcfsum+pvcf

  bondprice=pvcfsum
  return(bondprice)

getBondPrice(2000000,0.04,5,[0.010,0.015,0.020,0.025,0.030])

def getBondPrice_Z(face,couponrate,times,yc):
  pvcfsum=0
  cf=face*couponrate
  for t,y in zip(times,yc):
    pv=(1+y)**(-t)
    cashflow=cf if t<max(times) else (face+cf)
    pvcf=pv*cashflow
    pvcfsum+=pvcf

  bondprice=pvcfsum
  return(bondprice)

getBondPrice_Z(2000000,0.04,[1,1.5,3,4,7],[0.010,0.015,0.020,0.025,0.030])

def FizzBuzz(start, finish):
  outlist=[]
  for i in range(start,finish+1):
    if i%3==0 and i%5==0:
      outlist.append('FizzBuzz')
    elif i%3==0:
      outlist.append('Fizz')
    elif i%5==0:
      outlist.append('Buzz')
    else:
      outlist.append(i)

  return(outlist)

FizzBuzz(1,15)